upgrade jquery 1 and bootstrap 2 to latest minor
upgrading allows us to set $scope.thing to newThing without getting the
following error:
Error: Failed to execute 'insertBefore' on 'Node': The new child
element contains the parent.

we also had to upgrade bootstrap because we get the following error if
we try to run old bootstrap js with new jquery:
Uncaught TypeError: Cannot read property 'webkit' of undefined